#!/bin/bash
echo "SQL_SERVER_USER=$SQL_SERVER_USER_CODESPACES" > .env.codespaces
echo "SQL_SERVER_PASSWORD=$SQL_SERVER_PASSWORD_CODESPACES" >> .env.codespaces
echo "SQL_SERVER_CONTAINER_SERVICE=$SQL_SERVER_CONTAINER_SERVICE_CODESPACES" >> .env.codespaces